
require conf/machine/jetson-orin-nano-devkit-nvme.conf

require conf/machine/include/tegra-avt-common.inc

TEGRA_PLUGIN_MANAGER_OVERLAYS:append = " tegra234-p3767-camera-p3768-alvium-dual-19623-1x2-1x4.dtbo "