# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "alliedvision-tegra"
BBFILE_PATTERN_alliedvision-tegra = "^${LAYERDIR}/"
BBFILE_PRIORITY_alliedvision-tegra = "6"

LAYERDEPENDS_alliedvision-tegrar = "core tegra alliedvision"
LAYERSERIES_COMPAT_alliedvision-tegra = "scarthgap"

